#!/bin/sh

ROOT_PATH='/home/brunomiguel/Documents/data/BIDS_vswp/sub*'

for sub in $ROOT_PATH
do
  ROOT_SUBJECT=$sub/ses-001
  ROOT_ANAT=${ROOT_SUBJECT}/anat/

  fnpath_anat=${ROOT_ANAT}*T1w.nii.gz
  echo $fnpath_anat

  fsl_anat -i $fnpath_anat

done
